### ISSUE TITLE
Creating and importing necessary pages and files

### ISSUE THREAD

**Issue by ManikantaPotnuru9176** [contentql/pin-lottery#1]
**Use Typescript.**
- [x] get home one, contest all and contest details one, winners, all pages, contact page from template.
- [x] get styles folder from template.
- [x] remove en in top nav.
- [x] change logo.

**Comment by jagadeesh507** [comment]
- [ ] get home page one

**Comment by ManikantaPotnuru9176** [comment]
- [ ] contest page and its components.
- [ ] apply styles to the pages
