### ISSUE TITLE
Authentication Updates

### ISSUE THREAD

**Issue by ManikantaPotnuru9176** [contentql/pin-lottery#14]
- [x] Confirm password field with validation in signup and reset-password pages.
- [x] Remove password validation in login page.
- [x] Integrate toast.
- [x] Add toast notifications for authentication.
- [x] Forgot password email template types update.
- [x] Add username field in signup.
- [x] add seperate login validator.
- [x] Add logout functionality.

**Comment by akhil-naidu** [comment]
#16

**Comment by ManikantaPotnuru9176** [comment]
Popover for user profile - #18

**Comment by ManikantaPotnuru9176** [comment]
Update the color of input fields - #21
