### ISSUE TITLE
Soft Delete Plugin

### ISSUE THREAD

**Issue by akhil-naidu** [contentql/pin-lottery#143]
- [x] Create a new collection called Trash with three fields, one is the `collectionName` and `value`
- [x] For every collection in payload cms expect for trash, the trash createdAt is the deletedAt of the document.
- [x] If deleted in trash, it is permanently deleted.
- [x] Ensure this field was always hidden by default, we can use filedLevel hooks or condition
- [x] Before deleting the document, saved the id, collection_name and the entire_document_data in trash document
- [x] The trash collection will have a new attribute to restore the documents deleted
- [x] When restoring the document, we will create a new document with the existing value, by using `JSON.parse`, if possible we will try to retain the document id.
- [x] If we can restore the document id then working with realtionships would be ease
- [x] Discuss about access control

**Comment by akhil-naidu** [comment]
Example collection that requires trash functionality

```js
import type { CollectionConfig } from 'payload/types'

const ExampleCollection: CollectionConfig = {
  slug: 'example',
  hooks: {
    afterDelete: [
      async ({ req, doc }) => {
        const { payload } = req

        const trashDoc = {
          did: doc.id,
          collectionName: 'example', // should be same as slug
          value: doc,
        }

        // Assuming you have access to the Payload instance
        await payload.create({
          collection: 'trash',
          data: trashDoc,
        })
      },
    ],
  },
  fields: [
    {
      name: 'title',
      type: 'text',
    },
  ],
}

export default ExampleCollection

```

**Comment by akhil-naidu** [comment]
Custom Text Field

```jsx
import React from 'react'
import { useDocumentInfo } from 'payload/components/utilities'
import { Field } from 'payload/types'

const RestoreButton: React.FC = props => {
  const { id } = useDocumentInfo()
  return (
    <button
      onClick={async () => {
        await fetch(`/api/trash/restore/${id}`, {
          method: 'GET',
        })
      }}
    >
      Restore
    </button>
  )
}

const customTextField: Field = {
  name: 'collectionName',
  type: 'text',
  admin: {
    components: {
      afterInput: [RestoreButton],
    },
  },
}

export default customTextField

```

**Comment by akhil-naidu** [comment]
In `payload.config.ts`

```js
trashBin({
  displayToRoles: ['admin'] 
}),]
```
The displayToRoles assumes that there exists a `roles` field with hasMany and saveToJWT as true

or

```js
trashBin({}),
````

**Comment by ManikantaPotnuru9176** [comment]
trashBin({
      displayToRoles: ['admin'], // visible only to admins
      doNotEnableTrash: ['cart', 'wishlist', 'media'],
    }),

added a new option to disable sync for collections
