### ISSUE TITLE
Required Changes

### ISSUE THREAD

**Issue by ManikantaPotnuru9176** [contentql/pin-lottery#92]
### Frontend

- [x] login page top padding
- [x] category icons 
- [x] contest page scolling while adding filters
- [x] individual category fetching and brower more fetching
- [x] rounded corners for contests
- [x] revert the image in winner tab of contest
- [x] add padding for popover of user profile

### Admin Panel

- [x] remove add button in winner relation
- [x] make the title as user email in cart
- [x] auto selection in winners collection using fiterOptions

**Comment by ManikantaPotnuru9176** [comment]
Home Page: Write styles for buttons to hide them.


![Image](https://github.com/contentql/pin-lottery/assets/110469998/0a7739f8-8987-430a-b158-d14cad852713)

**Comment by ManikantaPotnuru9176** [comment]
- [ ] ticket number should be auto generated by nanoid and populate using default value.
- [ ] disable the buy tickets button in cart page which api is pending.
- [ ] cart changes : total price, delete
- [ ] get all tickets wihtout pagination in user page
- [ ] on clicking on the ticket redirect to the specific contest and add hover effect.
- [ ] check winner api.
- [ ] update all the contests with Days after threshold reached.
- [ ] local storage of tickets.
- [ ] confirm type of toasts

**Comment by ManikantaPotnuru9176** [comment]
**Admin Cred:**
Email: admin@lottery.com
Pass: Admin@123

**Comment by ManikantaPotnuru9176** [comment]
Frontend:

- [ ] Check my tickets page.
- [ ] Adjust the images in the carosel of the contest details page.
- [ ] login page issue in production ().


Admin panel:

- [ ] Hide the Contest timer status filed for the admin.
- [ ] If the admin unchecking the winner annouced status then uncheck the contest timer status, remove the winner relation and delete the winner.
- [ ] If the admin deleting a contest then show a confirmation popup.
- [ ] If the admin deleted a contest then delete all the related winners and tickets.
- [ ] If admin deleting a winner which has relation to a contest then show some warning.

**Comment by akhil-naidu** [comment]
- [ ] Ensure user role should not have access to creation of contest's and access to certain fields.
- [ ] Start with access control, in which a user role should only get data relavant to him, both in admin panel and in frontend
